[workspace]
resolver = "2"
members = [
    "examples/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
author = "Alekandr Medvedev"
description = "A collection of examples for the Vulkan API"

[workspace.dependencies]
ash = "0.38"
ash-window = "0.13"
winit = "0.30"
